### ISSUE TITLE
Marketwatch Doesn't Accept Login Request

### ISSUE THREAD

**Issue by TBye101** [kevindong/MarketWatch_API#1]
The following error occurs when trying to sign in via the example "driver.py"
I haven't changed anything, this is merely the example code executing.

HTTPConnectionPool(host='id.marketwatch.com', port=80): Max retries exceeded with url: /auth/submitlogin.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016A388216D8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

Any ideas?

**Comment by kevindong** [comment]
It looks like MarketWatch has changed the endpoints on which users authenticate themselves. 

I am no longer maintaining this project. But this project is licensed under the Apache license, so you're free to fork it and modify it as you'd like.
